modified the actions to check only package.xml and Cmake.lists files"

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -10,27 +10,26 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Set up ROS2
-      run: |
-        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
-        sudo curl -sSL http://repo.ros2.org/repos.key | sudo apt-key add -
-        sudo sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main jammy main" > /etc/apt/sources.list.d/ros2-latest.list'
-        sudo apt update && sudo apt install -y ros-humble-desktop
-
-    - name: Source ROS2
-      run: source /opt/ros/humble/setup.bash
-
     - name: Check Submissions
       run: |
-        for dir in submissions/*; do
-          if [ -d "$dir" ]; then
-            for subdir in "$dir"/*; do
-              if [ -d "$subdir" ]; then
-                if [ ! -f "$subdir/package.xml" ]; then
-                  echo "    Subdirectory $subdir is missing required files."
-                  exit 1
+        for main_dir in */; do
+          echo " Directory $main_dir is being checked"
+          if [ -d "$main_dir" ] && [ "$(ls -A "$main_dir")" ]; then
+              for dir in "$main_dir"/*; do
+                echo " Second level directory $dir is being checked"
+                if [ -d "$dir" ]; then
+                  for subdir in "$dir"/*; do
+                    echo " subdir $subdir is being checked"
+                    if [ -d "$subdir" ]; then
+                      if [ ! -f "$subdir/package.xml" ]; then
+                        echo "    Subdirectory $subdir is missing required files."
+                        exit 1
+                      fi
+                    fi
+                  done
                 fi
-              fi
-            done
+              done
+          else
+            echo "    Directory $main_dir is empty and will be skipped."
           fi
         done
