updated CI.yaml

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -21,19 +21,16 @@ jobs:
       run: source /opt/ros/humble/setup.bash
 
     - name: Check Submissions
-    run: |
-      for dir in submissions/*; do
-        if [ -d "$dir" ]; then
-        # echo "Checking submission: $dir"
-        for subdir in "$dir"/*; do
-            if [ -d "$subdir" ]; then
-                # echo "Checking subdirectory: $subdir"
+      run: |
+        for dir in submissions/*; do
+          if [ -d "$dir" ]; then
+            for subdir in "$dir"/*; do
+              if [ -d "$subdir" ]; then
                 if [ ! -f "$subdir/package.xml" ]; then
-                    echo "Subdirectory $subdir is missing required files."
-                    exit 1
+                  echo "    Subdirectory $subdir is missing required files."
+                  exit 1
                 fi
-            fi
+              fi
+            done
+          fi
         done
-        fi
-      done
-
